spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://fullstackspringbootdb.crxsddpjmuma.us-east-1.rds.amazonaws.com/fullstackspringbootdemo
    username: postgres
    password: Kierkegaard777!
    pool-size: 30