spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://<ebURL>/fullstackspringbootdemo
    username: <yourusername>
    password: <yourpassword>
    pool-size: 30