#Uncomment for AWS EB deployments
#spring:
#  profiles:
#    active: @spring.profiles.active@

server:
  port: 8081

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/<yourdb>
    username: <yourdbusername>
    password: <yourdbpassword>
    pool-size: 30